[허소정][feature/review] Add: review앱 생성 & 모델 작성
wecode-bootcamp-korea/13-BeautyOfFunction-backend pull request #3
Opened 2020-11-04 10:11 UTC by sojeong20

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Add: review앱 생성 & 모델 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-11-04 10:18 UTC, ulfrid requested changes
확인 부탁드립니다!

2020-11-04 10:18 UTC, ulfrid commented on review/models.py
> +
이 리뷰는 전체 상품에 대한거죠? 대상이 특정되지 않는데, ForeignKey 대상이 없나요? 지금 봤을땐 Category에 걸어야 할것 같다고 생각이 드는데요.

2020-11-04 12:19 UTC, sojeong20 commented on review/models.py
> +
참조하는 Foreign Key가 다른 앱에 있어서 merge되면 추가할게요

2020-11-04 13:19 UTC, ulfrid commented on review/models.py
> +
넵!

2020-11-05 04:40 UTC, ulfrid commented
LGTM

2020-11-05 04:40 UTC, merged